version: '2'

services:
  web:
    image: nginx:1.11-alpine
    links:
     - php
    ports:
      - "80:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/htdocs:/var/www/html
    volumes_from:
     - php
  db:
    image: mariadb:10.0.20
    command: "--innodb_use_native_aio=0"
    environment:
       - MYSQL_USER=root
       - MYSQL_ROOT_PASSWORD=1Vv4nfkCXp
       - MYSQL_PASSWORD=1Vv4nfkCXp
       - MYSQL_DATABASE=tosee
       - TZ=Europe/Moscow
    ports:
      - '3306:3306'
    volumes:
     - ./app/mysql:/var/lib/mysql