version: '2'

services:
  web:
    image: nginx:1.11-alpine
    links:
     - php
    ports:
      - "80:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/htdocs:/var/www/html
    volumes_from:
     - php
  php:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
     - "9000:9000"
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=192.168.0.103
    links:
      - db
    volumes:
      - ./app/htdocs:/var/www/html
      - ./app/php.ini:/usr/local/etc/php/conf.d/custom.ini
  db:
    image: mariadb:10.0.20
    environment:
       - MYSQL_USER=root
       - MYSQL_ROOT_PASSWORD=secret
       - MYSQL_PASSWORD=secret
       - MYSQL_DATABASE=tosee
    ports:
      - '3306:3306'
    volumes:
     - ./app/mysql:/var/lib/mysql
  #ежели не надо рубани
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - "8080:80"
    volumes:
     - /sessions
