version: '2'

services:
  php:
      image: docentovich/php.7.fpm-develop
      ports:
       - "9000:9000"
      environment:
        PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
#        XDEBUG_CONFIG: remote_host=127.0.0.1
      links:
        - db
      volumes:
        - ./app:/var/www/html
        - ./php-win-dev.ini:/usr/local/etc/php/conf.d/common.ini
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_ARBITRARY=1
      restart: always
      ports:
       - "8090:80"
      volumes:
       - C:\Users\AProzorov\prj\sessions
  web:
        image: nginx:1.11-alpine
        links:
         - php
        ports:
          - "80:80"
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
          - ./app:/var/www/html
        volumes_from:
         - php
  db:
        image: mysql:5.7.23
        environment:
           - MYSQL_USER=root
           - MYSQL_ROOT_PASSWORD=1Vv4nfkCXp
           - MYSQL_PASSWORD=1Vv4nfkCXp
           - MYSQL_DATABASE=tosee
           - TZ=Europe/Moscow
        ports:
          - '3306:3306'
        volumes:
         - ../mysql:/var/lib/mysql