version: '2'

services:
  web:
      image: nginx:1.11-alpine
      links:
       - php
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html
      volumes_from:
       - php
  db:
      image: mariadb:10.0.20
      command: "--innodb_use_native_aio=0"
      environment:
         - MYSQL_USER=root
         - MYSQL_ROOT_PASSWORD=1Vv4nfkCXp
         - MYSQL_PASSWORD=1Vv4nfkCXp
         - MYSQL_DATABASE=tosee
         - TZ=Europe/Moscow
      ports:
        - '3306:3306'
      volumes:
       - ./mysql:/var/lib/mysql
  php:
      image: docentovich/php.7.fpm-develop
      ports:
       - "9000:9000"
      links:
        - db
      volumes:
        - ./app/htdocs:/var/www/html
        - ./app/php-prod.ini:/usr/local/etc/php/conf.d/custom.ini