version: '2'

services:
  web:
      image: nginx
      ports:
        - "80:80"
      command: /var/www/run_nginx.sh
      env_file:
        - .env
      volumes:
        - ./run_nginx.sh:/var/www/run_nginx.sh
        - ./nginx.conf.template:/var/www/default.conf.template
        - ./env.php.template:/var/www/env.php.template
        - ./app:/var/www/html
        - ./php-prod.ini:/usr/local/etc/php/conf.d/custom.ini
  php:
      image: docentovich/php.7.fpm-develop
      ports:
        - "9000:9000"
      environment:
        PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
        XDEBUG_CONFIG: default_enable=0
      links:
        - db
        - web
      volumes_from:
        - web
  db:
      image: mysql:5.7.23
      environment:
         - MYSQL_ROOT_PASSWORD=1Vv4nfkCXp
         - MYSQL_DATABASE=tosee
         - TZ=Europe/Moscow
      command: --innodb_use_native_aio=0
      ports:
        - '3306:3306'
      volumes:
       - ../mysql:/var/lib/mysql
#  phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: phpmyadmin
#        environment:
#         - PMA_ARBITRARY=1
#        restart: always
#        ports:
#         - "8090:80"
#        volumes:
#         - C:\Users\AProzorov\prj\sessions